// Generated by CoffeeScript 1.4.0
(function() {

  $(function() {
    $('#test').css({
      'background-color': 'gray',
      'color': 'lightgray'
    });
    return $('#test').html('CoffeeScripted and LiveReloaded!');
  });

}).call(this);
